
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt_bq_project'
version: '1.0.0'
config-version: 2

vars:
  var_date: 6/11/2022

# This setting configures which "profile" dbt uses for this project.
profile: 'bigquery-db'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_modules"



## ---> forma manual Hooks
# on-run-start: insert into `onihanzo.dbt_hooks.audits`values('run_start',current_timestamp())
# on-run-end: insert into `onihanzo.dbt_hooks.audits`values('run_end',current_timestamp())


## ---> hook con macro
on-run-start: "{{insert_audits('run_star')}}"
on-run-end: "{{insert_audits('run_end')}}"



# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.

models:
  pre-hook: insert into `onihanzo.dbt_hooks.audits`values('model_start',current_timestamp())
  post-hook: insert into `onihanzo.dbt_hooks.audits`values('model_end',current_timestamp())

  dbt_bq_project:
    # Config indicated by + and applies to all files under models/example/
    example: # lo que estecen esta carpeta por defecto va a staging
      +materialized: view #crea una vista y no una tabla
      +schema: staging #added this part all tables loads in new schema
    # fake_model_3_materialization:
    #   core:
    #     materialized: table
    #   intermediate:
    #     materialized: ephemeral 